name    'occs-ab_gcc'
version '0.2.0'
source 'Custom'
author 'OCCS/AB'
license 'Apache License, Version 2.0'
summary 'Install the \"Development Tools\" group on RedHat family systems.'
description ''
project_page ''

