name    'occs-ab_tomcat'
version '0.1.0'
source 'UNKNOWN'
author 'occs'
license 'Public Domain'
summary 'Install Apache Tomcat for NLM OCCS/AB'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
