name    'occs-ab_tomcat'
version '0.2.1'
source 'https://github.com/danizen/puptent/ab_tomcat'
author 'occs'
license 'Public Domain'
summary 'Install Apache Tomcat for NLM OCCS/AB'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
